// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8ZQcij1l9Qc7WulZBML2B85jdZE46tMM',
    appId: '1:420745178947:android:d1261a68de10e45bb449f6',
    messagingSenderId: '420745178947',
    projectId: 'ygk-project-b2940',
    storageBucket: 'ygk-project-b2940.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpf-J288nffPM_ni2xy41-6Sa5ZShEgCU',
    appId: '1:420745178947:web:8beb9dccb7261268b449f6',
    messagingSenderId: '420745178947',
    projectId: 'ygk-project-b2940',
    authDomain: 'ygk-project-b2940.firebaseapp.com',
    storageBucket: 'ygk-project-b2940.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpf-J288nffPM_ni2xy41-6Sa5ZShEgCU',
    appId: '1:420745178947:web:9c7640bf129c1e84b449f6',
    messagingSenderId: '420745178947',
    projectId: 'ygk-project-b2940',
    authDomain: 'ygk-project-b2940.firebaseapp.com',
    storageBucket: 'ygk-project-b2940.firebasestorage.app',
  );

}